### ISSUE TITLE
HyDe is installed while make test does not worked

### ISSUE THREAD

**Issue by Yung-Chien** [pblischak/HyDe#14]
Hi @pblischak ,
I've finished the installation work of HyDe, but I got some error when I typed 'make test', the result as below,
`**** Testing run_hyde.py (full analysis). ****
run_hyde.py -i examples/snake-data.txt -m examples/snake-map.txt -n 52 -t 7 -s 8466 -o out
Traceback (most recent call last):
  File "/home1/xxx/miniconda2/envs/geno/bin/run_hyde.py", line 4, in <module>
    __import__('pkg_resources').run_script('phyde==0.4.3', 'run_hyde.py')
  File "/home1/xxx/miniconda2/envs/geno/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home1/xxx/miniconda2/envs/geno/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/run_hyde.py' not found in metadata at '/home1/xxx/software/HyDe/phyde.egg-info'
make: *** [Makefile:7: test] Error 1
`
So how could I fix this problem, or does this issue have any effect of following analyzation of HyDe?
Thanks in advances，
Yung-Chien

**Comment by pblischak** [comment]
Hi @Yung-Chien ,

This looks like a PATH error for the environment that you are using with Miniconda2. Did you install HyDe while the `geno` envorinment was active? Also, from the last bit, it looks like your computer is looking for the HyDe scripts in `/home1/xxx/software/HyDe`. How/where exactly did you install everything?

**Comment by Yung-Chien** [comment]
Hi @pblischak ,

Yes I installed HyDe when the geno envorinment was active, And definitely I compile and install the source at /home1/xxx/software/HyDe. However, I tried to reinstall HyDe in the base environment with a 2.7 version Python, it had the same error. More strangely, When I entered the script directory and type 
`python run_hyde.py -h`
I got this,
`usage: run_hyde.py [-h] -i -m -o -n -t -s [-tr] [-p]
                   [--prefix] [-q] [--ignore_amb_sites]

Options for run_hyde.py

optional arguments:
  -h, --help           show this help message and exit

required arguments:
  -i, --infile     name of the data input file
  -m, --map        map of individuals to taxa
  -o, --outgroup   name of the outgroup (only one accepted)
  -n, --num_ind    number of individuals in data matrix
  -t, --num_taxa   number of taxa (species, OTUs)
  -s, --num_sites  number of sites in the data matrix

additional arguments:
  -tr, --triples   table of triples to be analyzed
  -p, --pvalue     p-value cutoff for test of significance [default=0.05]
  --prefix           prefix appended to output files [default=hyde]
  -q, --quiet          supress printing to stdout
  --ignore_amb_sites   ignore missing/ambiguous sites
`

It seemed like a right output, so I was still confused about what kind of problems I got in the progress of installation. Thank you for answering my question.
Yung-Chien

**Comment by snehasjoshi** [comment]
Hi Yung-Chien
I am encountering the same problem. Can you please let me know how did you solve this?
