### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by rakeuler** [pblischak/HyDe#21]
I'm getting a segmentation fault error after it finishes reading the input file. I've been able to run this script with success on several other files, so I'm not sure what is causing this error now.

**Comment by rakeuler** [comment]
Well I was able to fix this but now I'm getting the following error:
/u@/h:/w/$run_hyde.py -i goodhundredalignment.txt -m mapTwelve.txt -o out1 -n 65 -t 12 -s 354651

Running run_hyde.py

Reading input file.................................................................Done.
Reading map file  .................................................................Done.
Traceback (most recent call last):
  File "/fslhome/rakeuler/miniconda3/bin/run_hyde.py", line 4, in <module>
    __import__('pkg_resources').run_script('phyde==0.4.3', 'run_hyde.py')
  File "/fslhome/rakeuler/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/fslhome/rakeuler/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/zhome/rakeuler/miniconda3/lib/python3.7/site-packages/phyde-0.4.3-py3.7-linux-x86_64.egg/EGG-INFO/scripts/run_hyde.py", line 140, in <module>
    data = hd.HydeData(infile, mapfile, outgroup, nind, ntaxa, nsites, quiet, ignore_amb_sites)
  File "phyde/core/data.pyx", line 130, in phyde.core.data.HydeData.__init__
KeyError: 'out1'

**Comment by pblischak** [comment]
Is 'out1' the name that you gave to your outgroup or is it just the name of one of the individuals in the outgroup taxon?

**Comment by rakeuler** [comment]
'out1' is the name I'd selected for the output file.

**Comment by pblischak** [comment]
Ah OK I see -- the `-o` flag is to specify the name of the outgroup taxon. If you want 'out1' to be the name for the output file then you can use `--prefix out1`

**Comment by rakeuler** [comment]
Thank you! This is what I get for copying parameters from old analyses rather than just reviewing documentation.

**Comment by pblischak** [comment]
No worries! Glad it is working
