### ISSUE TITLE
HyDe is installed but the test does not work

### ISSUE THREAD

**Issue by arturomarin** [pblischak/HyDe#6]
Hi,

I can install HyDe using the guide, but when I try the test whith make test it give me an error:

```
$ make test
**** Testing run_hyde.py (full analysis). ****
run_hyde.py -i examples/snake-data.txt -m examples/snake-map.txt -n 52 -t 7 -s 8466 -o out
Traceback (most recent call last):
  File "/home/amarin/miniconda2/bin/run_hyde.py", line 4, in <module>
    __import__('pkg_resources').run_script('phyde==0.4.2', 'run_hyde.py')
  File "/home/amarin/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/amarin/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1432, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/run_hyde.py' not found in metadata at '/home/amarin/miniconda2/lib/python2.7/site-packages/phyde-0.4.2.dist-info'
make: *** [test] Error 1

```

thanks in advance

**Comment by pblischak** [comment]
Hi there,

I'm not immediately sure what the problem could be but it could be worth it to try installing the package using pip.

If you're in the `HyDe/` directory that was cloned from GitHub, try running this command:

```
pip install -U .
```

**Comment by arturomarin** [comment]
Hi, 

the command does not work:
```
[root@DESEBDDOCKER01 HyDe]# pip install -U
ERROR: You must give at least one requirement to install (see "pip help install")
```
Is there something missing in the command?

**Comment by pblischak** [comment]
It's kind of hard to see, but the command should have a dot, `.`, after the `pip install -U`. This tells `pip` to build the package in the current directory.

```
pip install -U .
```

**Comment by arturomarin** [comment]
Thanks. Now I have another error:

```
[root@DESEBDDOCKER01 HyDe]# pip install -U .
Processing /root/HyDe
    Complete output from command python setup.py egg_info:
    ERROR:
      You are missing the following required modules:
      	 seaborn
    
    
    ERROR:
      Unable to install phyde.
      Please see the documentation at http://hybridization-detection.rtfd.io/.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-req-build-P9Eb4f/
[root@DESEBDDOCKER01 HyDe]# 

```
Is somethog stranger because seaborn is installed 

```
[root@DESEBDDOCKER01 ~]# pip install seaborn
Requirement already satisfied: seaborn in /usr/lib/python2.7/site-packages (0.9.0)
Requirement already satisfied: numpy>=1.9.3 in /usr/lib64/python2.7/site-packages (from seaborn) (1.15.2)
Requirement already satisfied: scipy>=0.14.0 in /usr/lib64/python2.7/site-packages (from seaborn) (1.1.0)
Requirement already satisfied: pandas>=0.15.2 in /usr/lib64/python2.7/site-packages (from seaborn) (0.23.4)
Requirement already satisfied: matplotlib>=1.4.3 in /usr/lib64/python2.7/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: pytz>=2011k in /usr/lib/python2.7/site-packages (from pandas>=0.15.2->seaborn) (2018.5)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/lib/python2.7/site-packages (from pandas>=0.15.2->seaborn) (2.7.3)
Requirement already satisfied: subprocess32 in /usr/lib64/python2.7/site-packages (from matplotlib>=1.4.3->seaborn) (3.5.2)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python2.7/site-packages (from matplotlib>=1.4.3->seaborn) (0.10.0)
Requirement already satisfied: six>=1.10 in /usr/lib/python2.7/site-packages (from matplotlib>=1.4.3->seaborn) (1.11.0)
Requirement already satisfied: backports.functools-lru-cache in /usr/lib/python2.7/site-packages (from matplotlib>=1.4.3->seaborn) (1.5)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/lib/python2.7/site-packages (from matplotlib>=1.4.3->seaborn) (2.2.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/lib64/python2.7/site-packages (from matplotlib>=1.4.3->seaborn) (1.0.1)
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=1.4.3->seaborn) (40.4.3)
[root@DESEBDDOCKER01 ~]# 


```

**Comment by pblischak** [comment]
Ok, so it looks like there is some miscommunication between where the packages are installed and where Python is looking for them. It looks like you are using Docker, so I went ahead and built a Docker image that should hopefully have everything installed correctly. The code below should get you started.

```bash
# 1. Pull the hyde-docker image
docker pull pblischak/hyde-docker

# 2. Run the image and connect the folder with you data so that you can analyze it
docker run -it -v </path/to/your/data>:/home pblischak/hyde-docker
```

Make sure you substitute `</path/to/your/data/>` with the actual path (and make sure the greater than and less than symbols are removed too). After that, you should be able to run the `run_hyde.py` script like in the documentation.

**Comment by arturomarin** [comment]
I apologize for the delay in answering. We had problems with the server hardware and had to stop installing programs on the server. You can close the issue, and if I try again to install the program and I have problems I will post an issue.

**Comment by pblischak** [comment]
No worries! I'm happy to help if need be
